"""Provisioning and SCIM public API."""

from .application import ProvisioningSource, ScimProvisioningService
from .group_application import ScimGroupProvisioningService
from .group_domain import ProvisioningGroup
from .group_scim import (
    SCIM_GROUP_SCHEMA,
    ScimGroupInput,
    ScimGroupListResponse,
    ScimGroupMember,
    ScimGroupPatchOperation,
    ScimGroupResource,
)
from .domain import (
    ProvisioningResourceId,
    ProvisioningResourceStatus,
    ProvisioningUser,
)
from .errors import (
    InvalidProvisioningResource,
    InvalidScimRequest,
    ProvisioningConflict,
    ProvisioningError,
    ProvisioningManagedStateConflict,
    ProvisioningPreconditionFailed,
    ProvisioningResourceNotFound,
    UnsupportedScimPatch,
)
from .http import (
    SCIM_ERROR_SCHEMA,
    SCIM_MEDIA_TYPE,
    SCIM_RESOURCE_TYPE_SCHEMA,
    SCIM_SCHEMA_SCHEMA,
    SCIM_SERVICE_PROVIDER_CONFIG_SCHEMA,
    ScimErrorResponse,
    ScimErrorType,
    ScimHttpResponse,
    ScimHttpTransport,
    ScimServiceProviderConfig,
    ScimUserFilter,
    ScimUserFilterExpression,
    parse_scim_patch_payload,
    parse_scim_user_payload,
    parse_user_filter,
    parse_user_filter_expression,
)
from .ports import ProvisioningGroupRepository, ProvisioningUserRepository
from .providers import (
    GENERIC_SCIM_PROFILE,
    MICROSOFT_ENTRA_PROFILE,
    OKTA_SCIM_PROFILE,
    ScimDeprovisionMode,
    ScimProviderKind,
    ScimProviderProfile,
    scim_provider_profile,
)
from .scim import (
    SCIM_LIST_RESPONSE_SCHEMA,
    SCIM_PATCH_SCHEMA,
    SCIM_USER_SCHEMA,
    ScimEmail,
    ScimListResponse,
    ScimMeta,
    ScimName,
    ScimPatchOperation,
    ScimPatchVerb,
    ScimUserInput,
    ScimUserResource,
    apply_user_patch,
)

__all__ = [
    "GENERIC_SCIM_PROFILE",
    "MICROSOFT_ENTRA_PROFILE",
    "OKTA_SCIM_PROFILE",
    "SCIM_ERROR_SCHEMA",
    "SCIM_GROUP_SCHEMA",
    "SCIM_LIST_RESPONSE_SCHEMA",
    "SCIM_MEDIA_TYPE",
    "SCIM_PATCH_SCHEMA",
    "SCIM_RESOURCE_TYPE_SCHEMA",
    "SCIM_SCHEMA_SCHEMA",
    "SCIM_SERVICE_PROVIDER_CONFIG_SCHEMA",
    "SCIM_USER_SCHEMA",
    "InvalidProvisioningResource",
    "InvalidScimRequest",
    "ProvisioningConflict",
    "ProvisioningError",
    "ProvisioningGroup",
    "ProvisioningGroupRepository",
    "ProvisioningManagedStateConflict",
    "ProvisioningPreconditionFailed",
    "ProvisioningResourceId",
    "ProvisioningResourceNotFound",
    "ProvisioningResourceStatus",
    "ProvisioningSource",
    "ProvisioningUser",
    "ProvisioningUserRepository",
    "ScimDeprovisionMode",
    "ScimEmail",
    "ScimErrorResponse",
    "ScimErrorType",
    "ScimGroupInput",
    "ScimGroupListResponse",
    "ScimGroupMember",
    "ScimGroupPatchOperation",
    "ScimGroupProvisioningService",
    "ScimGroupResource",
    "ScimHttpResponse",
    "ScimHttpTransport",
    "ScimListResponse",
    "ScimMeta",
    "ScimName",
    "ScimPatchOperation",
    "ScimPatchVerb",
    "ScimProviderKind",
    "ScimProviderProfile",
    "ScimProvisioningService",
    "ScimServiceProviderConfig",
    "ScimUserFilter",
    "ScimUserFilterExpression",
    "ScimUserInput",
    "ScimUserResource",
    "UnsupportedScimPatch",
    "apply_user_patch",
    "parse_scim_patch_payload",
    "parse_scim_user_payload",
    "parse_user_filter",
    "parse_user_filter_expression",
    "scim_provider_profile",
]
