"""Public authorization API."""

from .application import RoleCatalogApplicationService
from .audit import AuthorizationDecisionAuditRecorder
from .binding_application import RoleBindingApplicationService
from .domain.binding_value_objects import GrantSource, RoleBindingId, RoleBindingStatus
from .domain.decision import (
    AuthorizationDecision,
    AuthorizationDecisionId,
    AuthorizationReason,
    AuthorizationRequest,
    AuthorizationResult,
    DecisionExplanation,
    ExplanationLevel,
)
from .domain.errors import (
    AuthorizationModelError,
    InvalidGovernanceRule,
    InvalidPermissionCode,
    InvalidRoleBinding,
    InvalidRoleBindingTransition,
    InvalidRoleName,
    PermissionAlreadyAssigned,
    PermissionAlreadyExists,
    PermissionNotAssigned,
    PermissionNotFound,
    RoleAlreadyExists,
    RoleBindingAlreadyExists,
    RoleBindingNotFound,
    RoleHierarchyCycle,
    RoleHierarchyDepthExceeded,
    RoleHierarchyError,
    RoleHierarchyTenantMismatch,
    RoleHierarchyUnavailable,
    RoleInactive,
    RoleNotAssignable,
    RoleNotFound,
    RoleTenantMismatch,
    StaticSoDViolation,
)
from .domain.governance import (
    AuthorizationConstraint,
    DistinctActorSoDRule,
    GovernanceRuleId,
    GovernanceViolation,
    GovernanceViolationKind,
    MutuallyExclusiveRolesRule,
    NumericMaximumConstraint,
    ResourceAttributeEqualsConstraint,
    ResourceDescriptor,
    SeparationOfDutyRule,
)
from .domain.permission import Permission
from .domain.role import Role
from .domain.role_binding import RoleBinding
from .domain.value_objects import PermissionCode, RoleId, RoleStatus, RoleType
from .engine import AuthorizationDenied, AuthorizationEngine
from .governance import (
    AccessGovernanceApplicationService,
    ConstraintEvaluator,
    DynamicSoDEvaluator,
    StaticSoDEvaluator,
)
from .hierarchy import RoleHierarchyApplicationService, RoleHierarchyResolver
from .ports import (
    ConstraintRepository,
    PermissionCatalogRepository,
    RoleBindingRepository,
    RoleRepository,
    SoDRuleRepository,
)

__all__ = [
    "AccessGovernanceApplicationService",
    "AuthorizationConstraint",
    "AuthorizationDecision",
    "AuthorizationDecisionAuditRecorder",
    "AuthorizationDecisionId",
    "AuthorizationDenied",
    "AuthorizationEngine",
    "AuthorizationModelError",
    "AuthorizationReason",
    "AuthorizationRequest",
    "AuthorizationResult",
    "ConstraintEvaluator",
    "ConstraintRepository",
    "DecisionExplanation",
    "DistinctActorSoDRule",
    "DynamicSoDEvaluator",
    "ExplanationLevel",
    "GovernanceRuleId",
    "GovernanceViolation",
    "GovernanceViolationKind",
    "GrantSource",
    "InvalidGovernanceRule",
    "InvalidPermissionCode",
    "InvalidRoleBinding",
    "InvalidRoleBindingTransition",
    "InvalidRoleName",
    "MutuallyExclusiveRolesRule",
    "NumericMaximumConstraint",
    "Permission",
    "PermissionAlreadyAssigned",
    "PermissionAlreadyExists",
    "PermissionCatalogRepository",
    "PermissionCode",
    "PermissionNotAssigned",
    "PermissionNotFound",
    "ResourceAttributeEqualsConstraint",
    "ResourceDescriptor",
    "Role",
    "RoleAlreadyExists",
    "RoleBinding",
    "RoleBindingAlreadyExists",
    "RoleBindingApplicationService",
    "RoleBindingId",
    "RoleBindingNotFound",
    "RoleBindingRepository",
    "RoleBindingStatus",
    "RoleCatalogApplicationService",
    "RoleHierarchyApplicationService",
    "RoleHierarchyCycle",
    "RoleHierarchyDepthExceeded",
    "RoleHierarchyError",
    "RoleHierarchyResolver",
    "RoleHierarchyTenantMismatch",
    "RoleHierarchyUnavailable",
    "RoleId",
    "RoleInactive",
    "RoleNotAssignable",
    "RoleNotFound",
    "RoleRepository",
    "RoleStatus",
    "RoleTenantMismatch",
    "RoleType",
    "SeparationOfDutyRule",
    "SoDRuleRepository",
    "StaticSoDEvaluator",
    "StaticSoDViolation",
]
