"""Public API for the Authentication bounded context."""

from .application import AuthenticationApplicationService
from .domain import (
    AssuranceLevel,
    AuthenticationContext,
    AuthenticationError,
    AuthenticationMethod,
    AuthenticationSubjectInactive,
    Credential,
    CredentialAlreadyExists,
    CredentialId,
    CredentialNotFound,
    CredentialStatus,
    CredentialType,
    InvalidCredential,
    InvalidCredentialTransition,
    InvalidSession,
    InvalidSessionTransition,
    Session,
    SessionId,
    SessionNotFound,
    SessionStatus,
)
from .federation import (
    ExternalIdentityNotLinked,
    FederatedAssurance,
    FederatedAssuranceResolver,
    FederatedAuthenticationService,
    FederatedIdentityClaims,
    FederationError,
    IdentityTokenVerifier,
    InvalidFederationPolicy,
    InvalidIdentityToken,
)
from .ports import CredentialRepository, SessionRepository, TokenProvider
from .tokens import (
    AccessTokenClaims,
    ExpiredAccessToken,
    InvalidAccessToken,
    IssuedAccessToken,
    TokenConfigurationError,
    TokenError,
    TokenId,
    TokenSessionInactive,
    TokenType,
)

__all__ = [
    "AccessTokenClaims",
    "AssuranceLevel",
    "AuthenticationApplicationService",
    "AuthenticationContext",
    "AuthenticationError",
    "AuthenticationMethod",
    "AuthenticationSubjectInactive",
    "Credential",
    "CredentialAlreadyExists",
    "CredentialId",
    "CredentialNotFound",
    "CredentialRepository",
    "CredentialStatus",
    "CredentialType",
    "ExpiredAccessToken",
    "ExternalIdentityNotLinked",
    "FederatedAssurance",
    "FederatedAssuranceResolver",
    "FederatedAuthenticationService",
    "FederatedIdentityClaims",
    "FederationError",
    "IdentityTokenVerifier",
    "InvalidAccessToken",
    "InvalidCredential",
    "InvalidCredentialTransition",
    "InvalidFederationPolicy",
    "InvalidIdentityToken",
    "InvalidSession",
    "InvalidSessionTransition",
    "IssuedAccessToken",
    "Session",
    "SessionId",
    "SessionNotFound",
    "SessionRepository",
    "SessionStatus",
    "TokenConfigurationError",
    "TokenError",
    "TokenId",
    "TokenProvider",
    "TokenSessionInactive",
    "TokenType",
]
